### ISSUE TITLE
ECL not working with kernel version 22

### ISSUE THREAD

**Issue by tizoc** [Shen-Language/shen-cl#38]
Error when trying to run the tests is:

```
!!! FATAL ERROR: The variable |*macros*| is unbound.
Exiting Shen.
```

Probably has something to do with the changes introduced by the dynamic code expansion.

**Comment by tizoc** [comment]
I'm not familiar with ECL, but it is possible that for it to work the initialize function will have to be called at startup and not when building the binary.

**Comment by rkoeninger** [comment]
Right, in ECL, it doesn't emit a binary that has the global state persisted like for SBCL, CLisp and CCL. Anything you want to happen on startup needs to be under the `src/` directory at least. That's why the `DEFVAR`s like `*implementation*`, etc were moved to `primitives.lsp` from `boot.lsp` (old commit: https://github.com/Shen-Language/shen-cl/blob/90450b90a266fcf934e98c66ebaa1c0dfb52c1b2/install.lsp). The `initialise`s should probably be at the top of `overwrite.lsp` but not sure where exactly.

**Comment by tizoc** [comment]
I got ECL working on OSX, which helped a lot to test this.

Calling the initalise functions during startup fixes the problem.
